"""
ATT&CK Navigator layer export.

Generates a JSON layer file compatible with https://mitre-attack.github.io/attack-navigator/
Color codes each technique by its current detection status:
  - green  (#00c176): detected (covered in last window)
  - red    (#e60d0d): evaded (injected but not detected)
  - yellow (#f4d03f): uncovered (never injected or no data yet)

Usage:
    from mitre.navigator import export_navigator_layer
    path = export_navigator_layer(coverage_summary, output_dir="results")
"""

import json
from datetime import datetime
from pathlib import Path

# ATT&CK Navigator layer format v4.5
_LAYER_VERSION = "4.5"
_ATTACK_VERSION = "14"
_DOMAIN = "enterprise-attack"

# Status → color hex
_STATUS_COLORS = {
    "detected": "#00c176",   # green
    "evaded":   "#e60d0d",   # red
    "uncovered": "#f4d03f",  # yellow
}


def export_navigator_layer(coverage_summary: dict, output_dir: str = "results") -> str:
    """
    Build an ATT&CK Navigator layer from a coverage summary dict.

    Args:
        coverage_summary: output of CoverageMatrix.summary()
        output_dir: where to write the layer JSON

    Returns:
        Absolute path to the written file.
    """
    techniques_section = coverage_summary.get("techniques", {})
    coverage_pct = coverage_summary.get("coverage_percent", 0)
    ts = datetime.now().strftime("%Y%m%d_%H%M%S")

    technique_entries = []
    for tid, rec in techniques_section.items():
        status = rec.get("status", "uncovered")
        color = _STATUS_COLORS.get(status, _STATUS_COLORS["uncovered"])
        detection_rate = rec.get("detection_rate", 0)
        comment = (
            f"PurpleForge: {status} | "
            f"Detected {rec.get('detected', 0)}/{rec.get('injected', 0)} rounds | "
            f"Rules generated: {rec.get('rules_generated', 0)}"
        )
        entry = {
            "techniqueID": tid,
            "color": color,
            "comment": comment,
            "enabled": True,
            "metadata": [
                {"name": "status", "value": status},
                {"name": "detection_rate", "value": str(detection_rate)},
                {"name": "rules_generated", "value": str(rec.get("rules_generated", 0))},
            ],
            "score": int(detection_rate * 100),
        }
        # Handle subtechniques: T1110.001 → techniqueID stays as-is, Navigator handles them
        technique_entries.append(entry)

    layer = {
        "name": f"PurpleForge Coverage — {ts}",
        "versions": {
            "attack": _ATTACK_VERSION,
            "navigator": _LAYER_VERSION,
            "layer": _LAYER_VERSION,
        },
        "domain": _DOMAIN,
        "description": (
            f"Auto-generated by PurpleForge adversarial detection engineering. "
            f"Windowed coverage: {coverage_pct}%. "
            f"Generated: {datetime.now().isoformat()}"
        ),
        "filters": {"platforms": ["Windows"]},
        "sorting": 0,
        "layout": {
            "layout": "side",
            "aggregateFunction": "average",
            "showID": True,
            "showName": True,
        },
        "hideDisabled": False,
        "techniques": technique_entries,
        "gradient": {
            "colors": ["#ff6666", "#ffe766", "#8ec843"],
            "minValue": 0,
            "maxValue": 100,
        },
        "legendItems": [
            {"label": "Detected (covered)", "color": _STATUS_COLORS["detected"]},
            {"label": "Evaded (red winning)", "color": _STATUS_COLORS["evaded"]},
            {"label": "Uncovered", "color": _STATUS_COLORS["uncovered"]},
        ],
        "metadata": [],
        "links": [],
        "showTacticRowBackground": True,
        "tacticRowBackground": "#205b8f",
        "selectTechniquesAcrossTactics": True,
        "selectSubtechniquesWithParent": False,
        "selectVisibleTechniques": False,
    }

    out_dir = Path(output_dir)
    out_dir.mkdir(exist_ok=True)
    out_path = out_dir / f"navigator_layer_{ts}.json"
    out_path.write_text(json.dumps(layer, indent=2))
    return str(out_path)
